# Generated by Django 5.1.4 on 2026-07-08 19:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_usuario_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contacto_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('contacto_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('contacto_email', models.EmailField(blank=True, default='', max_length=254)),
                ('etapa', models.CharField(choices=[('NUEVO', 'Nuevo'), ('CONTACTADO', 'Contactado'), ('COTIZANDO', 'Cotizando'), ('NEGOCIACION', 'Negociación'), ('GANADO', 'Ganado'), ('PERDIDO', 'Perdido')], db_index=True, default='NUEVO', max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probabilidad', models.PositiveSmallIntegerField(default=30)),
                ('fuente', models.CharField(choices=[('WEB', 'Sitio web'), ('WHATSAPP', 'WhatsApp'), ('REFERIDO', 'Referido'), ('REDES', 'Redes sociales'), ('LOCAL', 'Visita al local'), ('OTRO', 'Otro')], default='WEB', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_cierre_estimada', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='clientes.cliente')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_oportunidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Correo'), ('REUNION', 'Reunión'), ('NOTA', 'Nota')], default='NOTA', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='clientes.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones', to=settings.AUTH_USER_MODEL)),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='crm.oportunidad')),
            ],
            options={
                'db_table': 'crm_interacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_crm', to='clientes.cliente')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='crm.oportunidad')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_crm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_tareas',
                'ordering': ['completada', 'fecha_vencimiento', '-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['etapa'], name='crm_oportun_etapa_92dfce_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidad',
            index=models.Index(fields=['cliente'], name='crm_oportun_cliente_1c2953_idx'),
        ),
    ]
