# Generated by Django 5.1.4 on 2026-07-03 03:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usuario_artesano_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PROPIETARIO', 'Propietario'), ('ARTESANO', 'Artesano'), ('CLIENTE', 'Cliente')], default='PROPIETARIO', max_length=20),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('NUEVA_COTIZACION_RAPIDA', 'Nueva cotización rápida web'), ('COTIZACION_APROBADA', 'Cotización aprobada'), ('PEDIDO_EN_PRODUCCION', 'Pedido en producción'), ('PEDIDO_LISTO', 'Pedido listo para entrega'), ('PEDIDO_ENTREGADO', 'Pedido entregado'), ('ALERTA_INVENTARIO', 'Alerta de inventario')], max_length=40)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('entidad_tipo', models.CharField(blank=True, max_length=30)),
                ('entidad_id', models.CharField(blank=True, max_length=36)),
                ('para_propietario', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
