# Generated by Django 5.1.4 on 2026-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('NUEVA_COTIZACION_RAPIDA', 'Nueva cotización rápida web'), ('COTIZACION_APROBADA', 'Cotización aprobada'), ('PEDIDO_EN_PRODUCCION', 'Pedido en producción'), ('PEDIDO_LISTO', 'Pedido listo para entrega'), ('PEDIDO_ENTREGADO', 'Pedido entregado'), ('PEDIDO_CANCELADO', 'Pedido cancelado'), ('ALERTA_INVENTARIO', 'Alerta de inventario')], max_length=40),
        ),
    ]
