# Generated by Django 5.1.4 on 2026-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='otp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
