# Generated by Django 5.1.4 on 2026-06-30 01:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('contacto_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('contacto_telefono', models.CharField(blank=True, default='', max_length=20)),
                ('contacto_email', models.EmailField(blank=True, default='', max_length=254)),
                ('tipo', models.CharField(choices=[('MATERIA_PRIMA', 'Materia Prima'), ('SERVICIO', 'Servicio'), ('AMBOS', 'Ambos')], default='MATERIA_PRIMA', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proveedores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['ruc'], name='proveedores_ruc_a5d69c_idx'), models.Index(fields=['activo'], name='proveedores_activo_068092_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('EN_PROCESO', 'En Proceso'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_inicio_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('monto_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_creadas', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='pedidos.pedido')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'ordenes_trabajo',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='ordenes_tra_estado_9aace9_idx'), models.Index(fields=['proveedor'], name='ordenes_tra_proveed_418aff_idx')],
            },
        ),
    ]
