# Generated by Django 5.1.4 on 2026-07-23 03:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_actualizaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRapida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('CONVERTIDA', 'Convertida a cotización'), ('IGNORADA', 'Ignorada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('cotizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='cotizaciones.cotizacion')),
                ('usuario_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_rapidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes_rapidas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
