# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0003_solicitudrapida"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="configuracion",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="solicitudrapida",
            name="personalizacion",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
