# Generated by Django 5.1.4 on 2026-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_material_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dimensiones',
            field=models.CharField(blank=True, help_text="Medidas reales del mueble, ej: '130 × 100 cm · Soporta 500 lb'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(choices=[('MIMBRE', 'Mimbre (natural)'), ('POLIALUMINIO', 'Polialuminio (Tetrapack reciclado)'), ('COMBINADO', 'Combinado (mimbre y polialuminio)'), ('TOTORA', 'Totora (fibra natural)')], default='COMBINADO', max_length=20),
        ),
    ]
