// Ciudades del Ecuador para selectores (capitales provinciales y ciudades principales).
export const CIUDADES_ECUADOR = [
  'Quito',
  'Guayaquil',
  'Cuenca',
  'Ambato',
  'Azogues',
  'Babahoyo',
  'Baños de Agua Santa',
  'Cayambe',
  'Chone',
  'Daule',
  'Durán',
  'El Coca (Fco. de Orellana)',
  'Esmeraldas',
  'Guaranda',
  'Ibarra',
  'La Libertad',
  'Latacunga',
  'Loja',
  'Macas',
  'Machala',
  'Manta',
  'Milagro',
  'Montecristi',
  'Nueva Loja (Lago Agrio)',
  'Otavalo',
  'Portoviejo',
  'Puyo',
  'Quevedo',
  'Riobamba',
  'Salinas',
  'Samborondón',
  'Sangolquí (Valle de los Chillos)',
  'Santa Elena',
  'Santo Domingo',
  'Tena',
  'Tulcán',
  'Zamora',
] as const
