# Generated by Django 5.1.4 on 2026-06-30 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(choices=[('METRO', 'Metro lineal'), ('METRO2', 'Metro cuadrado'), ('KG', 'Kilogramo'), ('UNIDAD', 'Unidad'), ('ROLLO', 'Rollo')], max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_primas', to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'materias_primas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=50, unique=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_suministrados', to='proveedores.proveedor')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.materiaprima')),
            ],
            options={
                'db_table': 'lotes',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_al_momento', models.DecimalField(decimal_places=3, max_digits=10)),
                ('revisada', models.BooleanField(default=False)),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.materiaprima')),
            ],
            options={
                'db_table': 'alertas_stock',
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada por compra'), ('SALIDA_PRODUCCION', 'Salida por inicio de producción'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('DEVOLUCION', 'Devolución a proveedor')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_antes', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock_despues', models.DecimalField(decimal_places=3, max_digits=10)),
                ('justificacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.lote')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.materiaprima')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_inventario', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_en_productos', to='inventario.materiaprima')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='catalogo.producto')),
            ],
            options={
                'db_table': 'producto_materia',
                'unique_together': {('producto', 'materia_prima')},
            },
        ),
    ]
