# Generated by Django 5.1.4 on 2026-06-30 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedula_ruc', models.CharField(db_index=True, max_length=13, unique=True)),
                ('nombre_completo', models.CharField(db_index=True, max_length=200)),
                ('tipo', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('EMPRESA', 'Empresa / Persona Jurídica')], default='NATURAL', max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['cedula_ruc'], name='clientes_cedula__489823_idx'), models.Index(fields=['nombre_completo'], name='clientes_nombre__c1af84_idx'), models.Index(fields=['activo'], name='clientes_activo_1f6d14_idx')],
            },
        ),
    ]
