# Generated by Django 5.1.4 on 2026-07-03 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario_cuenta',
            field=models.OneToOneField(blank=True, help_text='Cuenta de acceso del cliente al portal web', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_vinculado', to=settings.AUTH_USER_MODEL),
        ),
    ]
