# Generated by Django 5.1.4 on 2026-07-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_tarea_produccion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tareaproduccion',
            name='unique_pedido_tipo_tarea',
        ),
        migrations.AlterUniqueTogether(
            name='tareaproduccion',
            unique_together={('pedido', 'tipo')},
        ),
    ]
