# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_pedido_tracking_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="configuracion",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
